// Juz (Parts) display names in Arabic and English
const List<Map<String, dynamic>> juzNames = [
  {"id": 1, "arabic": "الجزء الأول", "english": "Juz 1"},
  {"id": 2, "arabic": "الجزء الثاني", "english": "Juz 2"},
  {"id": 3, "arabic": "الجزء الثالث", "english": "Juz 3"},
  {"id": 4, "arabic": "الجزء الرابع", "english": "Juz 4"},
  {"id": 5, "arabic": "الجزء الخامس", "english": "Juz 5"},
  {"id": 6, "arabic": "الجزء السادس", "english": "Juz 6"},
  {"id": 7, "arabic": "الجزء السابع", "english": "Juz 7"},
  {"id": 8, "arabic": "الجزء الثامن", "english": "Juz 8"},
  {"id": 9, "arabic": "الجزء التاسع", "english": "Juz 9"},
  {"id": 10, "arabic": "الجزء العاشر", "english": "Juz 10"},
  {"id": 11, "arabic": "الجزء الحادي عشر", "english": "Juz 11"},
  {"id": 12, "arabic": "الجزء الثاني عشر", "english": "Juz 12"},
  {"id": 13, "arabic": "الجزء الثالث عشر", "english": "Juz 13"},
  {"id": 14, "arabic": "الجزء الرابع عشر", "english": "Juz 14"},
  {"id": 15, "arabic": "الجزء الخامس عشر", "english": "Juz 15"},
  {"id": 16, "arabic": "الجزء السادس عشر", "english": "Juz 16"},
  {"id": 17, "arabic": "الجزء السابع عشر", "english": "Juz 17"},
  {"id": 18, "arabic": "الجزء الثامن عشر", "english": "Juz 18"},
  {"id": 19, "arabic": "الجزء التاسع عشر", "english": "Juz 19"},
  {"id": 20, "arabic": "الجزء العشرون", "english": "Juz 20"},
  {"id": 21, "arabic": "الجزء الحادي والعشرون", "english": "Juz 21"},
  {"id": 22, "arabic": "الجزء الثاني والعشرون", "english": "Juz 22"},
  {"id": 23, "arabic": "الجزء الثالث والعشرون", "english": "Juz 23"},
  {"id": 24, "arabic": "الجزء الرابع والعشرون", "english": "Juz 24"},
  {"id": 25, "arabic": "الجزء الخامس والعشرون", "english": "Juz 25"},
  {"id": 26, "arabic": "الجزء السادس والعشرون", "english": "Juz 26"},
  {"id": 27, "arabic": "الجزء السابع والعشرون", "english": "Juz 27"},
  {"id": 28, "arabic": "الجزء الثامن والعشرون", "english": "Juz 28"},
  {"id": 29, "arabic": "الجزء التاسع والعشرون", "english": "Juz 29"},
  {"id": 30, "arabic": "الجزء الثلاثون", "english": "Juz 30"},
];
